[tool.poetry]
name = "hold-win"
version = "0.1.0"
description = ""
authors = ["Aliaksand Akhromenka <‘kartmander@gmail.com’>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
